### ISSUE TITLE
Compatibility with Klaviyo v0.6.0 Package

### ISSUE THREAD

**Issue by jmussitsch** [fivetran/dbt_shopify_holistic_reporting#17]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The latest version of dependent package Klaviyo is 0.6.0. This package requires < 0.6.0:

```
- package: fivetran/klaviyo
  version: [">=0.5.0", "<0.6.0"]
```

### Are you interested in contributing this feature?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

We can't upgrade Klaviyo to v0.6.0 because we use this package as well.

**Comment by fivetran-reneeli** [comment]
Hi @jmussitsch thanks for bringing this up-- a new release for Klaviyo is underway currently. Hence we plan to update this dependency after it is live!

Renee

**Comment by fivetran-reneeli** [comment]
Hi @jmussitsch, we just released updates for this package (now v0.5.0) to reflect the underlying changes to the  dependency versions!

```
packages:
- package: fivetran/shopify
  version: [">=0.10.0", "<0.11.0"]
- package: fivetran/klaviyo
  version: [">=0.7.0", "<0.8.0"]
```

As such will be closing this out.
