### ISSUE TITLE
[Feature] Increment packages

### ISSUE THREAD

**Issue by fivetran-catfritz** [fivetran/dbt_shopify_holistic_reporting#19]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Packages currenty:
```yml
- package: fivetran/shopify
  version: [">=0.10.0", "<0.11.0"]
- package: fivetran/klaviyo
  version: [">=0.7.0", "<0.8.0"]
```

need to be:
Packages currenty:
```yml
- package: fivetran/shopify
  version: [">=0.11.0", "<0.13.0"]
- package: fivetran/klaviyo
  version: [">=0.7.0", "<0.8.0"]
```

### Are you interested in contributing this feature?

- [x] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

### Anything else?

Made the range bigger since we're about to release a breaking update to shopify. Also need this updated for use in fivetran_utils testing.
